### PR TITLE
assertions for remove_funs.R

### PR DESCRIPTION
**Pull request by grewered**
how strict do I need to be here?

I didn't add assertions for remove(Non)Numeric, because I wasn't sure what input exactly should be excluded. (everything that is not in ""? should i exclude strings in data frames?
it's similar with crop: is this function supposed to accept numeric input of any kind? because atm it does and it just converts it to characters.

### CODE REVIEW

**Comment by sachseka** [comment]
> how strict do I need to be here?
> 
> I didn't add assertions for remove(Non)Numeric, because I wasn't sure what input exactly should be excluded. (everything that is not in ""? should i exclude strings in data frames? it's similar with crop: is this function supposed to accept numeric input of any kind? because atm it does and it just converts it to characters.

I wouldn't accept data.frames in removeNumeric nor in crop. I think these functions are designed to handle vectors or just strings...

**Comment by grewered** [comment]
when one of you gives their ok, should i merge then or wait until both of you gave their ok?

**Comment by weirichs** [comment]
> when one of you gives their ok, should i merge then or wait until both of you gave their ok?

If one of us approves, you're welcome to merge. Thanks a lot!

**Comment by grewered** [comment]
I wasn't sure about this one. because I changed something more. Can I merge this, too @weirichs ?

**Review by sachseka — APPROVED** [review]

**Pull request merged**
